// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXWFSQ68HyR4uC0OMGm0zg1e-twmxfFUA',
    appId: '1:261744102257:web:51513ba0d55bed5a2544d0',
    messagingSenderId: '261744102257',
    projectId: 'zajel-hub',
    authDomain: 'zajel-hub.firebaseapp.com',
    storageBucket: 'zajel-hub.firebasestorage.app',
    measurementId: 'G-BK5BEEXDN3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2L8Dg1ZGh846G6_K3S9vWQjcM2UZK8Nw',
    appId: '1:261744102257:ios:fb3b4689639cae1d2544d0',
    messagingSenderId: '261744102257',
    projectId: 'zajel-hub',
    storageBucket: 'zajel-hub.firebasestorage.app',
    iosBundleId: 'com.example.zajelHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2L8Dg1ZGh846G6_K3S9vWQjcM2UZK8Nw',
    appId: '1:261744102257:ios:fb3b4689639cae1d2544d0',
    messagingSenderId: '261744102257',
    projectId: 'zajel-hub',
    storageBucket: 'zajel-hub.firebasestorage.app',
    iosBundleId: 'com.example.zajelHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXWFSQ68HyR4uC0OMGm0zg1e-twmxfFUA',
    appId: '1:261744102257:web:d12c3b09867aab662544d0',
    messagingSenderId: '261744102257',
    projectId: 'zajel-hub',
    authDomain: 'zajel-hub.firebaseapp.com',
    storageBucket: 'zajel-hub.firebasestorage.app',
    measurementId: 'G-H6HK2HQXBT',
  );
}
